### ISSUE TITLE
Exception has occurred: CLR/System.InvalidOperationException

### ISSUE THREAD

**Issue by mammadkoma** [VahidN/DNTIdentity#33]
![image](https://user-images.githubusercontent.com/17564001/51902401-222ba980-23cf-11e9-8bab-ad12fbefec72.png)

after run by vscode : 
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.Relational.dll but was not handled in user code: 'Relational-specific methods can only be used when the context is using a relational database provider.'
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at ASPNETCoreIdentitySample.Services.Identity.IdentityDbInitializer.Initialize() in E:\Projects\DNTIdentity\src\ASPNETCoreIdentitySample.Services\Identity\IdentityDbInitializer.cs:line 64
   at ASPNETCoreIdentitySample.IocConfig.IdentityServicesRegistry.callDbInitializer(IApplicationBuilder app) in E:\Projects\DNTIdentity\src\ASPNETCoreIdentitySample.IocConfig\IdentityServicesRegistry.cs:line 40
   at ASPNETCoreIdentitySample.IocConfig.IdentityServicesRegistry.UseCustomIdentityServices(IApplicationBuilder app) in E:\Projects\DNTIdentity\src\ASPNETCoreIdentitySample.IocConfig\IdentityServicesRegistry.cs:line 31
   at ASPNETCoreIdentitySample.Startup.Configure(ILoggerFactory loggerFactory, IApplicationBuilder app, IHostingEnvironment env) in E:\Projects\DNTIdentity\src\ASPNETCoreIdentitySample\Startup.cs:line 83

**Comment by VahidN** [comment]
Have you change anything? because the `Relational-specific methods can only be used when the context is using a relational database provider.` error message means you are not using the default `LocalDB` database.

**Comment by mammadkoma** [comment]
I have not installed any sql sever on my pc because of the network policies.
How can I run this projects by other local or in memory db just for see the demo?

**Comment by VahidN** [comment]
- Installing [LocalDB](https://download.microsoft.com/download/E/F/2/EF23C21D-7860-4F05-88CE-39AA114B014B/SqlLocalDB.msi) is very easy. [more info](https://www.dotnettips.info/post/2409/localdb-faq)
- You can define different [connecting strings here](ConnectionStrings) and then [use them](https://github.com/VahidN/DNTIdentity/blob/1793cff9d94a74508b1f2510ec9252a3d3a28c6a/src/ASPNETCoreIdentitySample.DataLayer/Context/DbContextOptionsExtensions.cs#L48).
