### ISSUE TITLE
خطا در صفحه مدیریت کاربران پس از ارتقاء به نسخه netcore2.2

### ISSUE THREAD

**Issue by rezaeiy** [VahidN/DNTIdentity#37]
با سلام
پس از ارتقاء نسخه دات نت در صفحه مدیریت کاربران -قسمت صفحه بندی خطا بوجود میاد
/identity/usersmanager

<cs-pager cs-paging-pagesize ...
```
System.NullReferenceException: Object reference not set to an instance of an object
at cloudscribe.Web.Pagination.PagerTagHelper.Process(TagHelperContext context, TagHelperOutput output)

   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)

   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)

```

```

**Comment by VahidN** [comment]
<div dir="rtl">

پس از ارتقاء به [sdk-2.2.300](https://github.com/VahidN/DNTIdentity/commit/08968f78be8d385e4310ede56441e7e0ee6dde13) مشكلي مشاهده نشد

**Comment by rezaeiy** [comment]
سلام و عرض ادب
از طریق توضیحات این [لینک ](https://github.com/cloudscribe/cloudscribe.Web.Pagination/issues/44#issuecomment-454941528)مشکل حل شد

` options.EnableEndpointRouting = false;`

**Comment by VahidN** [comment]
هيچ مشكلي وجود نداشت كه بخواهد حل شود. دقيقا دو صفحه‌ي نمايش ليست كاربران و نمايش ليست لاگ‌ها را قبل از ارسال نظر قبلي شخصا آزمايش كرده بودم
